edition: 1.0.0
name: container-pytorch
access: default
vars:
  region: cn-shanghai
services:
  pytorch-demo:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: pytorch-service
      function:
        name: pytorch-function
        timeout: 60
        caPort: 9000
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: 'registry.cn-shanghai.aliyuncs.com/custom-container/pytorch-demo:0.0.1'
